from .FavouriteQariCreateAPIView import * # noqa
from .FavouriteQariListAPIView import * # noqa
from .FavouriteZikrCreateAPIView import * # noqa
from .FavouriteZikrListAPIView import * # noqa
from .FavouriteBookCreateAPIView import * # noqa
from .FavouriteBookListAPIView import * # noqa
from .FavouriteAudioBookCreateAPIView import * # noqa
from .FavouriteAudioBookListAPIView import * # noqa
from .FavouriteNarrativeCreateAPIView import * # noqa
from .FavouriteNarrativeListAPIView import * # noqa